# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs: 
  node: circleci/node@4.1
jobs:
  slither:
      docker: 
        - image: trailofbits/eth-security-toolbox
      steps:
        - checkout
        - node/install-yarn
        - node/install-packages: 
            override-ci-command: yarn install
        - run:
            name: run slither
            command: solc-select 0.6.12 && slither . --print human-summary
workflows:
  # Name the workflow "welcome"
  deploy:
    # Run the welcome/run job in its own container
    jobs:
      - slither
